package com.jamith.booksformecustomer.util;

public enum OrderStatus {
    ORDER_CONFIRMED, ORDER_COMPLETED, ORDER_FAILED, ORDER_CANCELLED, ORDER_REJECTED, ORDER_APPROVED, PAYMENT_STATUS_APPROVED, PAYMENT_STATUS_REJECTED, PAYMENT_PENDING;
}
